Geo field index
qdrant/bfb pull request #13
Opened 2023-10-08 18:58 UTC by IvanPleshkov

### All Submissions:

* [ ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-10-09 07:08 UTC, timvisee requested changes

2023-10-09 07:08 UTC, timvisee commented on Cargo.toml
> +serde_json = "~1.0"
Please sort the list of dependencies alphabetically :smile:

2023-10-09 07:08 UTC, timvisee commented on src/common.rs
> +                "lat": BERLIN.lat + rand::thread_rng().gen_range(-GEO_RADIUS..GEO_RADIUS),
```suggestion
                "lon": BERLIN.lon + rand::thread_rng().gen_range(-GEO_RADIUS..=GEO_RADIUS),
                "lat": BERLIN.lat + rand::thread_rng().gen_range(-GEO_RADIUS..=GEO_RADIUS),
```

2023-10-09 07:08 UTC, timvisee commented on src/common.rs
> +                }),
Should we randomize the center and range here? With this configurations, all points are always included.

2023-10-26 14:22 UTC, IvanPleshkov commented on Cargo.toml
> +serde_json = "~1.0"
done

2023-10-30 16:18 UTC, timvisee commented on src/common.rs
> +                }),
> Not all points, square is larger

Good point. Thanks for clarifying.

2023-10-30 16:18 UTC, timvisee approved these changes

2024-09-10 14:21 UTC, closed without merging